
output "alb_dns_name" {
  description = "Public DNS name of the ALB"
  value       = aws_lb.app_alb.dns_name
}

output "ec2_public_ip" {
  description = "Public IP of the EC2 instance"
  value       = aws_instance.web.public_ip
}

output "rds_endpoint" {
  description = "RDS endpoint"
  value       = aws_db_instance.db.address
  sensitive   = false
}

output "rds_password_note" {
  description = "The RDS master password is generated by Terraform (random_password.db_password.result)"
  value       = "Password is generated by Terraform state; do not commit your state file to VCS."
}
